UNARY_TEST_CASE(successor, -1, 0)
UNARY_TEST_CASE(successor, 0, 1)
UNARY_TEST_CASE(successor, 1, 2)
UNARY_TEST_CASE(predecessor, 2, 1)
UNARY_TEST_CASE(predecessor, 1, 0)
UNARY_TEST_CASE(predecessor, 0, -1)
UNARY_TEST_CASE(twice, 0, 0)
UNARY_TEST_CASE(twice, 1, 2)
UNARY_TEST_CASE(twice, 2, 4)
UNARY_TEST_CASE(twice, -1, -2)
UNARY_TEST_CASE(half_nonnegative, 0, 0)
UNARY_TEST_CASE(half_nonnegative, 1, 0)
UNARY_TEST_CASE(half_nonnegative, 2, 1)
UNARY_TEST_CASE(half_nonnegative, 3, 1)
UNARY_TEST_CASE(half_nonnegative, 4, 2)
UNARY_TEST_CASE(half_nonnegative, 5, 2)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 0, 0, 0)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 0, 1, 0)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 1, 0, 1)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 1, 1, 0)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 2, 0, 2)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 2, 1, 1)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 2, 2, 0)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 3, 0, 3)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 3, 1, 1)
BINARY_TEST_CASE(binary_scale_down_nonnegative, 3, 2, 0)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 0, 0, 0)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 0, 1, 0)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 0, 2, 0)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 1, 0, 1)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 1, 1, 2)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 1, 2, 4)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 2, 0, 2)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 2, 1, 4)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 2, 2, 8)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 3, 0, 3)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 3, 1, 6)
BINARY_TEST_CASE(binary_scale_up_nonnegative, 3, 2, 12)
UNARY_TEST_CASE(positive, -1, false)
UNARY_TEST_CASE(positive, 0, false)
UNARY_TEST_CASE(positive, 1, true)
UNARY_TEST_CASE(positive, 2, true)
UNARY_TEST_CASE(negative, -1, true)
UNARY_TEST_CASE(negative, 0, false)
UNARY_TEST_CASE(negative, 1, false)
UNARY_TEST_CASE(negative, 2, false)
UNARY_TEST_CASE(zero, -1, false)
UNARY_TEST_CASE(zero, 0, true)
UNARY_TEST_CASE(zero, 1, false)
UNARY_TEST_CASE(zero, 2, false)
UNARY_TEST_CASE(one, -1, false)
UNARY_TEST_CASE(one, 0, false)
UNARY_TEST_CASE(one, 1, true)
UNARY_TEST_CASE(one, 2, false)
UNARY_TEST_CASE(even, -1, false);
UNARY_TEST_CASE(even, 0, true);
UNARY_TEST_CASE(even, 1, false);
UNARY_TEST_CASE(even, 2, true);
UNARY_TEST_CASE(odd, -1, true);
UNARY_TEST_CASE(odd, 0, false);
UNARY_TEST_CASE(odd, 1, true);
UNARY_TEST_CASE(odd, 2, false);
